location: 80634
interval: 60000 # 10 seconds
stores:
  - R521 # OEZ
  - R045 # Munich Center
parts:
  - MTUX3ZD/A # iPhone 15 Pro 128GB Natur
  - MTV53ZD/A # iPhone 15 Pro 256GB Natur
  - MTV03ZD/A # iPhone 15 Pro 128GB Blau
  - MTV63ZD/A # iPhone 15 Pro 256GB Blau
  - MTUV3ZD/A # iPhone 15 Pro 128GB Black
  - MTV13ZD/A # iPhone 15 Pro 256GB Black
notifications:
  alwaysNotify: false
